### ISSUE TITLE
wtf?!

### ISSUE THREAD

**Issue by binjospookie** [Komar0ff/ludka#1]
https://github.com/Komar0ff/ludka/blob/bc6ea2f75121f95de8cb638f8bb2e1f715f8ce0d/src/App.js#L40

какого хера здесь так мало фраз? где же великие "ёбаный рот этого казино?" 
гои не оценили

**Comment by johnthecat** [comment]
Можно использовать Web Audio API для улучшения UX, звуки предлагаю взять [отсюда](https://stalker.fandom.com/ru/wiki/%D0%91%D0%B0%D0%BD%D0%B4%D0%B8%D1%82%D1%8B-%D0%B3%D1%80%D0%B0%D0%B1%D0%B8%D1%82%D0%B5%D0%BB%D0%B8/%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8)

**Comment by binjospookie** [comment]
и вибрации мощнейшие добавить 
чтобы мобильным юзерам было кайфово

**Comment by binjospookie** [comment]
автор, ау!

**Comment by Komar0ff** [comment]
проиграл

**Comment by binjospookie** [comment]
говна поел, братан (с)
